site_name: Kassow Robots Vision Manual
site_description: Example Kassow Robots integration for the wenglor robot vision API.
site_url: https://wenglor.github.io/wenglor-kassow-vision/
repo_url: https://github.com/wenglor/wenglor-kassow-vision
repo_name: wenglor-kassow-vision
use_directory_urls: true

theme:
  name: material
  logo: images/wenglor_logo.svg
  features:
    - navigation.indexes
    - content.code.copy
    - toc.integrate
    - search.highlight

nav:
  - index.md
  - 1. Installation of CBuns:
    - 1_0_installation_of_cbuns/index.md
  - 2. Set up Workcell:
    - 2_0_set_up_workcell/index.md
  - 3. Robot Program:
    - 3_0_robot_program/index.md
  - 4. Troubleshooting:
    - 4_0_troubleshooting/index.md
  - 5. Support & Feedback:
    - 5_0_support_and_feedback/index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.snippets

docs_dir: docs

extra:
  generator: false

copyright: "© 2025 wenglor sensoric group"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/image_format.css
  - css/wenglor.css